//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElectionManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Party
    {
        public int Id { get; set; }
        public string Partyname { get; set; }
        public string Senator { get; set; }
        public decimal Age { get; set; }
        public int Votes { get; set; }
        public string Logourl { get; set; }
    }
}
